apiVersion: apps/v1
kind: Deployment
metadata:
  name: regapp-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: regapp-web
  template:
    metadata:
      labels:
        app: regapp-web
    spec:
      containers:
      - name: regapp-web
        image: regapp-web:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: regapp-web-service
spec:
  selector:
    app: regapp-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort